### ISSUE TITLE
Use node-pre-gyp

### ISSUE THREAD

**Issue by geovie** [Timeular/noble-mac#1]
We should use node-pre-gyp to provide pre build native modules

**Comment by paulvarache** [comment]
I support this. Can we use travis' matrix build feature to prebuild for the `electron` runtime as well?
```yaml
os: osx
language: node_js
node_js:
  - "8.6.0"
env: 
  - NODE_RUNTIME=node TARGET=8.6.0
  - NODE_RUNTIME=electron TARGET=2.0.0 DIST_URL=https://atom.io/download/atom-shell
install:
  - yarn
  - yarn global add node-pre-gyp node-pre-gyp-github aws-sdk
  - node-pre-gyp configure --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
  - node-pre-gyp build --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
  - node-pre-gyp package --runtime=$NODE_RUNTIME --target=$TARGET --dist-url=$DIST_URL
  - node-pre-gyp-github publish --release
```

I have this minimal travis config and it does build for both runtime. See: https://github.com/paulvarache/noble-mac/releases/tag/0.0.1
